# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib ciber
NULL

dataFrameShuffle <- function(df) {
    .Call('_ciber_dataFrameShuffle', PACKAGE = 'ciber', df)
}

